### ISSUE TITLE
have images fit mobile

### ISSUE THREAD

**Issue by JoePiscapo** [GavickPro/News-Show-Pro-GK5#298]
Hey Tomasz,

Is it possible to add some CSS code to make all images fit to the width of a mobile phone?

Thanks,
Mike

**Comment by dziudek** [comment]
Hello,

Please add:

```css
.nspArt img.nspImage { 
	max-width: 100%;
}
```

in the below media-query:

https://github.com/GavickPro/News-Show-Pro-GK5/blob/J!3.0_compatible/mod_news_pro_gk5/interface/css/style.css#L464-L468
