### ISSUE TITLE
News Show Pro GK5 on smartphone

### ISSUE THREAD

**Issue by robertosalviGK5** [GavickPro/News-Show-Pro-GK5#358]
Hi, I have a problem with GK5 in smartphone display on the site http://www.diocesi.parma.it/diocesi_2015/: the news on pc are displayed with proper spacing (please see this image: http: //www.diocesi. parma.it/GK5onPC.jpg), while the same news on smartphone are displayed in a paddng exaggerated (please see this image: http://www.diocesi.parma.it/GK5onSmartphone.jpg): how can I reduce the space around news only in viewing on smartphones, so that they become like this example http://www.diocesi.parma.it/GK5onSmartphone2.jpg?
Many thanks

**Comment by dziudek** [comment]
Hello,

Please in your template mobile CSS code the following fragment:

```css
.nspArts, 
.nspLinksWrap {
    padding: 0!important;
}
.nspArt {
    padding: 0 0 15px 0!important;
}
```
