### ISSUE TITLE
GK5 1.9.3.6 - Pagination

### ISSUE THREAD

**Issue by kuzco9x** [GavickPro/News-Show-Pro-GK5#373]
I used to use the GK5 on joomla 2.5.28, but after upgraded to Joomla 3.2.0, the GK5's pagination itself have number inside dots. 
Like this
[http://baohiembaolong.vn/news.PNG](url)
and its quite inconvenience.
Anybody help me with this issue!?
Thanks a lot.

**Comment by dziudek** [comment]
Please try to add in your template CSS file:

```css
.nspPagination li {
    text-indent: -9999px!important;
}
```
